services:
  frontend:
    environment:
      - NODE_ENV=development
    volumes:
      - ../src/frontend:/workspaces/src/frontend
  backend:
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../:/workspaces/parliament-attendance